### ISSUE TITLE
Alter builds to only test languages where that language's code has changed

### ISSUE THREAD

**Issue by edy-cf** [codefellows/data-structures-and-algorithms#50]
Right now, no matter what code you change in this repo, all code will be tested. We should change that, via GitHub Actions.

**Comment by edy-cf** [comment]
Depends on #7 and #11 being finished first.

**Comment by johncokos** [comment]
Found this ... https://github.community/t/run-job-only-if-folder-changed/118292

Yikes.

```yaml
jobs:
  check:
    name: Check files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != db/* ]]; then
              echo "This modified file is not under the 'db' folder."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  job_for_db:
    name: Job for 'db' folder
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: run for 'db' folder
        run: echo "This job runs only when all the modified files are under the 'db' folder."
```
